[package]
name = "wim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lexical = "6.1.1"
libc = "0.2.139"
log = "0.4.17"
rune = "0.12.1"
simple-logging = "2.0.2"
stackfmt = "0.1.2"
thiserror = "1.0.39"
